apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fiapx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: fiapx/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: fiapx-secrets, key: POSTGRES_USER }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: fiapx-secrets, key: POSTGRES_PASSWORD }
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef: { name: fiapx-config, key: POSTGRES_DB }
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: { name: fiapx-secrets, key: JWT_SECRET }
            - name: AUTH_PORT
              value: "8081"
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fiapx
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
